DROP TABLE IF EXISTS Account;

CREATE TABLE Account (id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(30),
balance DECIMAL(15,4),
currency VARCHAR(15)
);

CREATE TABLE Transfer (id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
fromId INTEGER,
toId INTEGER,
amount DECIMAL(15,4),
transferStatus VARCHAR
);

